services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_USER=demo'
      - 'POSTGRES_PASSWORD=demo'
    ports:
      - '15432:5432'
  redis:
    image: 'redis:7-alpine'
    ports:
      - '16379:6379'
